# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo apt install sshpass
      - run: npm i
      - run: npm run build
      - run: npm run export
      - name: Hello world action
        shell: bash
        run: sshpass -p "${{ secrets.SSH_PASS }}" scp -o StrictHostKeyChecking=no -r ./out/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/marte.dev/.
      # - uses: cross-the-world/scp-pipeline@v1.2.1
      #   with:
      #     local: "./out/*"
      #     remote: "/var/www/marte.dev/."
      #     host: ${{ secrets.SSH_HOST }}
      #     user: ${{ secrets.SSH_USER }}
      #     pass: ${{ secrets.SSH_PASS }}
